#+TITLE: Download Household Pulse Survey


* Overview of the project

This project is to download the Public Use Files (PUF) of the Household Pulse Survey
from the Census Bureau. The link to the PUF is
https://www.census.gov/programs-surveys/household-pulse-survey/datasets.html.

To download the all PUF data files, just run =cmd_download_puf.R=. The code will
download the zipped SAS file for each week, unzip and read the data into R, and
save the output data.

* Explanation of the R code.

- =cmd_initiate.R= :: Set up the project folders.
- =cmd_download_puf.R= :: Download the PUF SAS data files.
  - In the first time to run the data, change the variable ~neweeks~ from ~NULL~
    to ~1:N~ where ~N~ is the latest week when the PUF is available, e.g.,
    ~1:24~ from weeks 1 to 24.
  - To avoid repeating the whole downloading process whenever new data are
    available, you can change ~oldweeks~ to ~neweeks~ and re-define ~newweeks~
    to the latest week, e.g., ~oldweeks = 1:24~ and ~newweeks = 25:27~.
  - The output of this file is a ~.rds~ file in the =output_data= folder.
  - The file also checks the availability of variables in each week.

* Documentation

The =documentation= folder contains the official documents from the Household
Pulse Survey as well as a variable dictionary for all variables available in
each week.
