#+TITLE: Download Household Pulse Survey


* Overview of the project

This project is to download the Public Use Files (PUF) of the Household Pulse Survey
from the Census Bureau. The link to the PUF is
https://www.census.gov/programs-surveys/household-pulse-survey/datasets.html.

To download the all PUF data files, just run =cmd_download_puf.R=. The code will
download the zipped SAS file for each week, unzip and read the data into R, and
save the output data.

* Explanation of the R code.
- [[file:master.R][master.R]] :: Run this file to complete the whole process.
  + When it is your first time to run the code, do the following
    1) Change the root directory (Line 3).
    2) Change ~neweeks~ to ~1:T~ where ~T~ is the latest week of the HPS survey.
    3) Change ~oldweeks~ to ~NULL~.
    4) After running the code, change ~neweeks~ to ~NULL~, and change ~oldweeks~ to
       ~1:T~.
    5) If you want the output data file is a CSV file, you need to change
       ~output.format~ to ~"csv"~ (Line 21).

  + Whenever the PUF for new weeks is available, change ~neweeks~ to these new weeks.

  + IMPORTANT! You may fail to download some files which are big so that the
    "timeout" of downloading is used up. If it happens, unpon finishing the
    downloading process, there will be a message that shows downloading for
    which weeks fails. Then, you need to manually download them, save and rename
    them to the folder of =input_data/pulse/sas/weekTT.zip= where =TT= is the
    two-digit zero-padding integer for the week.

Two component files in ~master.R~ are
- =cmd_initiate.R= :: Set up the project folders.
- =cmd_download_puf.R= :: Download the PUF SAS data files.
  - The output of this file is a ~.rds~ file in the =output_data= folder.
  - The file also checks the availability of variables in each week.

* Documentation

The =documentation= folder contains the official documents from the Household
Pulse Survey as well as a variable dictionary for all variables available in
each week.
